# Generated by Django 5.2.7 on 2026-01-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_announcementcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='instructor',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='course',
            field=models.CharField(choices=[('CRIM', 'Criminology'), ('PSY', 'Psychology'), ('CS', 'Computer Science'), ('EDUC', 'Education'), ('HM', 'Hospitality Management'), ('IT', 'Information Technology')], default='IT', max_length=10),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='instructor_name',
            field=models.CharField(default='TBA', max_length=120),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='section',
            field=models.CharField(default='A', max_length=50),
        ),
        migrations.DeleteModel(
            name='EventAnnouncement',
        ),
    ]
